/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Main;
import Model.Percobaan;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class ClassificationFrame extends javax.swing.JFrame {

    Main main;
    Percobaan hasil_percobaan;
    HashMap<String, String> konfigurasi_pso;
    
    public ClassificationFrame(Main main) {
        initComponents();
        this.main = main;
    }

    private ClassificationFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        custome_percobaan = new javax.swing.JPanel();
        validation_custome = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        k_custome = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        input_k_fold = new javax.swing.JSpinner();
        algorithm_custome = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        Generasi_panel = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        label_input_generasi = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        populasi_panel = new javax.swing.JPanel();
        populasi_ = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        label_input_populasi = new javax.swing.JTextField();
        c1_panel = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        label_input_c1 = new javax.swing.JTextField();
        c2_panel = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        label_input_c2 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        mulaiKlasifikasi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        log_result_k = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lihatData = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_hasil_cross_validation = new javax.swing.JTable();
        log_result = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        scrollpanel_log = new javax.swing.JScrollPane();
        panel_log = new javax.swing.JPanel();
        button = new javax.swing.JPanel();
        simpanPercobaan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rerata_nb = new javax.swing.JLabel();
        rerata_nbpso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Classification Window");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        custome_percobaan.setBackground(new java.awt.Color(0, 0, 204));
        custome_percobaan.setPreferredSize(new java.awt.Dimension(250, 80));
        custome_percobaan.setLayout(new javax.swing.BoxLayout(custome_percobaan, javax.swing.BoxLayout.PAGE_AXIS));

        validation_custome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        validation_custome.setPreferredSize(new java.awt.Dimension(305, 75));
        validation_custome.setLayout(new javax.swing.BoxLayout(validation_custome, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel30.setPreferredSize(new java.awt.Dimension(304, 30));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        jLabel10.setText("Cross Validation");
        jPanel30.add(jLabel10, java.awt.BorderLayout.CENTER);

        validation_custome.add(jPanel30);

        k_custome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        k_custome.setLayout(new javax.swing.BoxLayout(k_custome, javax.swing.BoxLayout.LINE_AXIS));

        jPanel38.setPreferredSize(new java.awt.Dimension(47, 83));

        jLabel15.setText("K-Fold");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        k_custome.add(jPanel38);

        input_k_fold.setAutoscrolls(true);
        input_k_fold.setPreferredSize(new java.awt.Dimension(99, 20));
        k_custome.add(input_k_fold);

        validation_custome.add(k_custome);

        custome_percobaan.add(validation_custome);

        algorithm_custome.setLayout(new javax.swing.BoxLayout(algorithm_custome, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setMinimumSize(new java.awt.Dimension(300, 194));
        jPanel23.setPreferredSize(new java.awt.Dimension(300, 429));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setPreferredSize(new java.awt.Dimension(304, 20));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        jLabel9.setText("Algoritma Klasifikasi");
        jPanel26.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel26);

        jPanel25.setPreferredSize(new java.awt.Dimension(310, 337));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jPanel28.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(jPanel28);

        jPanel25.add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.PAGE_AXIS));

        Generasi_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Generasi_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        Generasi_panel.setLayout(new javax.swing.BoxLayout(Generasi_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel34.setPreferredSize(new java.awt.Dimension(100, 10));
        jPanel34.setLayout(new java.awt.BorderLayout());

        label_input_generasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_generasi.setText("10");
        label_input_generasi.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel34.add(label_input_generasi, java.awt.BorderLayout.CENTER);

        jPanel33.setPreferredSize(new java.awt.Dimension(100, 83));

        jLabel13.setText("Generasi");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        jPanel34.add(jPanel33, java.awt.BorderLayout.LINE_START);

        Generasi_panel.add(jPanel34);

        jPanel29.add(Generasi_panel);

        populasi_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        populasi_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        populasi_panel.setLayout(new javax.swing.BoxLayout(populasi_panel, javax.swing.BoxLayout.LINE_AXIS));

        populasi_.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel11.setText("Populasi");

        javax.swing.GroupLayout populasi_Layout = new javax.swing.GroupLayout(populasi_);
        populasi_.setLayout(populasi_Layout);
        populasi_Layout.setHorizontalGroup(
            populasi_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(populasi_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        populasi_Layout.setVerticalGroup(
            populasi_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        populasi_panel.add(populasi_);

        jPanel35.setLayout(new java.awt.BorderLayout());

        label_input_populasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_populasi.setText("5");
        jPanel35.add(label_input_populasi, java.awt.BorderLayout.CENTER);

        populasi_panel.add(jPanel35);

        jPanel29.add(populasi_panel);

        c1_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c1_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        c1_panel.setLayout(new javax.swing.BoxLayout(c1_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel36.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel12.setText("c1");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        c1_panel.add(jPanel36);

        jPanel37.setLayout(new java.awt.BorderLayout());

        label_input_c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_c1.setText("2");
        label_input_c1.setEnabled(false);
        jPanel37.add(label_input_c1, java.awt.BorderLayout.CENTER);

        c1_panel.add(jPanel37);

        jPanel29.add(c1_panel);

        c2_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c2_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        c2_panel.setLayout(new javax.swing.BoxLayout(c2_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel40.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel14.setText("c2");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        c2_panel.add(jPanel40);

        jPanel41.setLayout(new java.awt.BorderLayout());

        label_input_c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_c2.setText("2");
        label_input_c2.setEnabled(false);
        jPanel41.add(label_input_c2, java.awt.BorderLayout.CENTER);

        c2_panel.add(jPanel41);

        jPanel29.add(c2_panel);

        jPanel25.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel25);

        jPanel24.setPreferredSize(new java.awt.Dimension(304, 20));
        jPanel24.setLayout(new java.awt.BorderLayout());

        mulaiKlasifikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/start.png"))); // NOI18N
        mulaiKlasifikasi.setText("Cross Validation");
        mulaiKlasifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulaiKlasifikasi.setPreferredSize(new java.awt.Dimension(105, 20));
        mulaiKlasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiKlasifikasiActionPerformed(evt);
            }
        });
        jPanel24.add(mulaiKlasifikasi, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel24);

        algorithm_custome.add(jPanel23);

        custome_percobaan.add(algorithm_custome);

        jPanel2.add(custome_percobaan);

        jPanel4.setPreferredSize(new java.awt.Dimension(680, 602));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        log_result_k.setMaximumSize(new java.awt.Dimension(2147483647, 130));
        log_result_k.setMinimumSize(new java.awt.Dimension(23, 130));
        log_result_k.setPreferredSize(new java.awt.Dimension(599, 130));
        log_result_k.setLayout(new javax.swing.BoxLayout(log_result_k, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(599, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/list.png"))); // NOI18N
        jLabel1.setText("Akurasi K Cross Validation");

        lihatData.setText("Data");
        lihatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                .addComponent(lihatData))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(lihatData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        log_result_k.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(599, 60));
        jPanel6.setLayout(new java.awt.BorderLayout());

        tabel_hasil_cross_validation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "K", "NB (%)", "NBPSO (%)"
            }
        ));
        jScrollPane1.setViewportView(tabel_hasil_cross_validation);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        log_result_k.add(jPanel6);

        jPanel3.add(log_result_k);

        log_result.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.BorderLayout());

        scrollpanel_log.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollpanel_log.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        panel_log.setLayout(new javax.swing.BoxLayout(panel_log, javax.swing.BoxLayout.PAGE_AXIS));
        scrollpanel_log.setViewportView(panel_log);

        jPanel7.add(scrollpanel_log, java.awt.BorderLayout.CENTER);

        log_result.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(log_result);

        button.setMaximumSize(new java.awt.Dimension(32767, 30));
        button.setMinimumSize(new java.awt.Dimension(100, 30));
        button.setPreferredSize(new java.awt.Dimension(599, 30));

        simpanPercobaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        simpanPercobaan.setText("Simpan");
        simpanPercobaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanPercobaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPercobaanActionPerformed(evt);
            }
        });

        jLabel2.setText("Rata-rata Akurasi NB : ");

        jLabel3.setText("Rata-rata Akurasi NBPSO : ");

        rerata_nb.setText("0 %");

        rerata_nbpso.setText("0 %");

        javax.swing.GroupLayout buttonLayout = new javax.swing.GroupLayout(button);
        button.setLayout(buttonLayout);
        buttonLayout.setHorizontalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rerata_nb)
                .addGap(69, 69, 69)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rerata_nbpso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(simpanPercobaan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonLayout.setVerticalGroup(
            buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLayout.createSequentialGroup()
                .addGroup(buttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPercobaan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(rerata_nb)
                    .addComponent(rerata_nbpso))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(button);

        jPanel4.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiKlasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiKlasifikasiActionPerformed
        int kfold = Integer.parseInt(this.input_k_fold.getModel().getValue().toString());
        konfigurasi_pso = new HashMap<String, String>();
        if(kfold > 1){
            try{
            konfigurasi_pso.put("Generasi",this.label_input_generasi.getText());
            konfigurasi_pso.put("Populasi", this.label_input_populasi.getText());
            konfigurasi_pso.put("c1", this.label_input_c1.getText());
            konfigurasi_pso.put("c2", this.label_input_c2.getText());
            this.hasil_percobaan = this.main.doClassificationData(kfold, konfigurasi_pso);
            this.setTabelData();   
          }catch(Exception e){
              JOptionPane.showMessageDialog(null,"Parameter salah atau tidak lengkap","Ooops!",JOptionPane.ERROR_MESSAGE);     
          }    
        }
        else{
            JOptionPane.showMessageDialog(null,"K fold jangan 0 atau 1, dak tau cakmano nak baginyo","Deeh!!",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_mulaiKlasifikasiActionPerformed

    private void simpanPercobaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPercobaanActionPerformed
        if(this.hasil_percobaan == null || this.konfigurasi_pso == null){
            JOptionPane.showMessageDialog(null,"Lakukan Percobaan terlebih dahulu","Ooops!",JOptionPane.ERROR_MESSAGE);
        }else{
            this.main.simpanPercobaan(hasil_percobaan, konfigurasi_pso);    
        }
    }//GEN-LAST:event_simpanPercobaanActionPerformed

    private void lihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataActionPerformed
        this.main.tampilkanFrameData();
    }//GEN-LAST:event_lihatDataActionPerformed
    
    private void setTabelData(){
         DefaultTableModel tabel = (DefaultTableModel) this.tabel_hasil_cross_validation.getModel();
         tabel.setRowCount(0);
         Object[] object;
         int index = 0;
         for(Double akurasi : this.hasil_percobaan.getAkurasi_nb()){
             object = new Object[3];
             object[0] = " "+(index+1);
             object[1] = this.hasil_percobaan.getAkurasi_nb().get(index);
             object[2] = this.hasil_percobaan.getAkurasi_nbpso().get(index);
             tabel.addRow(object);
             index++;
         }
         this.centeringTable();
         this.panel_log.removeAll();
         this.drawLogResult();
         this.drawRerataAkurasi();
    }
    
     private void centeringTable(){
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
       for(int i=0;i<this.tabel_hasil_cross_validation.getColumnCount();i++){
           this.tabel_hasil_cross_validation.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
       }    
    }
     
    private void drawRerataAkurasi(){
        this.rerata_nb.setText(this.hasil_percobaan.getRerata("akurasi NB")+" %");
        this.rerata_nbpso.setText(this.hasil_percobaan.getRerata("akurasi NBPSO")+" %");
    }
    
    
    private void drawLogResult(){
        int index_k = 0;
        this.drawToPanel("  Generasi : "+this.konfigurasi_pso.get("Generasi"));
        this.drawToPanel("  Populasi : "+this.konfigurasi_pso.get("Populasi"));
        this.drawToPanel("  C1       : "+this.konfigurasi_pso.get("c1"));
        this.drawToPanel("  C2       : "+this.konfigurasi_pso.get("c2"));
        this.drawToPanel(" ");
        for(double[] bobot_k : this.hasil_percobaan.getBobot()){
            this.drawToPanel("  K"+(index_k+1)+" (waktu eksekusi nb : "+this.hasil_percobaan.getWaktu_eksekusi_nb().get(index_k)+""
                    + "(detik), waktu eksekusi nbpso : "+this.hasil_percobaan.getWaktu_eksekusi_nbpso().get(index_k)+"(detik))");
            for(int i=0;i<bobot_k.length;i++){
              this.drawToPanel("  Bobot Fitur "+(i+1)+"   : "+bobot_k[i]);
            }
            this.drawToPanel(" ");
            index_k++;
        }
        this.drawToPanel("  Rata-rata waktu eksekusi NB         : "+this.hasil_percobaan.getRerata("waktu NB")+" (detik)");
        this.drawToPanel("  Rata-rata waktu eksekusi NBPSO : "+this.hasil_percobaan.getRerata("waktu NBPSO")+" (detik)");
        this.drawToPanel(" ");
    }
    
    private void drawToPanel(String text){
        JPanel panel;
        JLabel label;
        panel = new JPanel(new BorderLayout());
        panel.setBackground(Color.WHITE);
        label = new JLabel(text);
        panel.add(label);
        this.panel_log.add(panel);
        this.panel_log.validate();
        this.panel_log.repaint();
        this.scrollpanel_log.revalidate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassificationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Generasi_panel;
    private javax.swing.JPanel algorithm_custome;
    private javax.swing.JPanel button;
    private javax.swing.JPanel c1_panel;
    private javax.swing.JPanel c2_panel;
    private javax.swing.JPanel custome_percobaan;
    private javax.swing.JSpinner input_k_fold;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel k_custome;
    private javax.swing.JTextField label_input_c1;
    private javax.swing.JTextField label_input_c2;
    private javax.swing.JTextField label_input_generasi;
    private javax.swing.JTextField label_input_populasi;
    private javax.swing.JButton lihatData;
    private javax.swing.JPanel log_result;
    private javax.swing.JPanel log_result_k;
    private javax.swing.JButton mulaiKlasifikasi;
    private javax.swing.JPanel panel_log;
    private javax.swing.JPanel populasi_;
    private javax.swing.JPanel populasi_panel;
    private javax.swing.JLabel rerata_nb;
    private javax.swing.JLabel rerata_nbpso;
    private javax.swing.JScrollPane scrollpanel_log;
    private javax.swing.JButton simpanPercobaan;
    private javax.swing.JTable tabel_hasil_cross_validation;
    private javax.swing.JPanel validation_custome;
    // End of variables declaration//GEN-END:variables
}
