/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Main;
import Controller.Skenario;
import Model.Percobaan;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import javafx.scene.paint.Color;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author M.Hakim Amransyah
 */
public class MainFrame extends javax.swing.JFrame {

    private Main main_controller;
    private ArrayList<Skenario> daftar_skenario;
    
    public MainFrame(Main main, ArrayList<Skenario> daftar_skenario) {
        initComponents();
        this.main_controller = main;
        this.daftar_skenario = daftar_skenario;
        this.drawListSkenario();
        this.enableKonfigurasiPSO(false);
    }

    private MainFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        Home_Panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        Main_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        custome_skenario_pengujian = new javax.swing.JPanel();
        create_scnearion = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        nama_skenario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        awal_du = new javax.swing.JSpinner();
        akhir_du = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        awal_dl = new javax.swing.JSpinner();
        akhir_dl = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        buatSkenario = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        lihatPartisiData = new javax.swing.JButton();
        list_scenario = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_skenario = new javax.swing.JList<>();
        jPanel18 = new javax.swing.JPanel();
        hapusSkenario = new javax.swing.JButton();
        custome_pengujian = new javax.swing.JPanel();
        Daftar_percobaan = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_percobaan = new javax.swing.JTable();
        hapusPercobaan = new javax.swing.JButton();
        custome_algorithm = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        opsi_pso = new javax.swing.JRadioButton();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        Generasi_panel = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        label_stoping_criteria = new javax.swing.JComboBox<>();
        jPanel34 = new javax.swing.JPanel();
        label_input_stoping_point = new javax.swing.JTextField();
        populasi_panel = new javax.swing.JPanel();
        populasi_ = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        label_input_populasi = new javax.swing.JTextField();
        c1_panel = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        label_input_c1 = new javax.swing.JTextField();
        c2_panel = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        label_input_c2 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        mulaiKlasifikasi = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel45 = new javax.swing.JPanel();
        log_panel = new javax.swing.JPanel();
        label_tipe = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        label_akurasi = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        label_porsi_dl = new javax.swing.JLabel();
        label_porsi_du = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        label_jumlah_dl = new javax.swing.JLabel();
        label_jumlah_du = new javax.swing.JLabel();
        panel_PSO_konf = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        label_generasi = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        label_populasi = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        label_c1 = new javax.swing.JLabel();
        label_c2 = new javax.swing.JLabel();
        label_bobot_fitur = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        label_rerata_akurasi_skenario = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        label_log_skenario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tugas Akhir Aboe");

        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Home_Panel.setLayout(new java.awt.BorderLayout());

        jLabel35.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel35.setText("Klasifikasi Penderita Penyakit Parkinson");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setText("Naive Bayes");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel37.setText("- Particle Swarm Optimization");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addContainerGap(348, Short.MAX_VALUE))
        );

        Home_Panel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Home", Home_Panel);

        Main_panel.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        custome_skenario_pengujian.setBackground(new java.awt.Color(204, 204, 255));
        custome_skenario_pengujian.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        custome_skenario_pengujian.setPreferredSize(new java.awt.Dimension(300, 602));
        custome_skenario_pengujian.setLayout(new javax.swing.BoxLayout(custome_skenario_pengujian, javax.swing.BoxLayout.PAGE_AXIS));

        create_scnearion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        create_scnearion.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        create_scnearion.setMinimumSize(new java.awt.Dimension(150, 100));
        create_scnearion.setPreferredSize(new java.awt.Dimension(295, 300));
        create_scnearion.setLayout(new javax.swing.BoxLayout(create_scnearion, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel12.setPreferredSize(new java.awt.Dimension(295, 30));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jPanel13.setPreferredSize(new java.awt.Dimension(70, 200));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        jLabel6.setText("Skenario Pengujian");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13);

        create_scnearion.add(jPanel12);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMinimumSize(new java.awt.Dimension(110, 30));
        jPanel4.setPreferredSize(new java.awt.Dimension(295, 20));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setPreferredSize(new java.awt.Dimension(70, 54));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Nama");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        nama_skenario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel11.add(nama_skenario, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel11);

        create_scnearion.add(jPanel4);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setBackground(new java.awt.Color(0, 0, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(50, 113));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Data Uji");

        awal_du.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        awal_du.setToolTipText("awal data uji");

        akhir_du.setModel(new javax.swing.SpinnerNumberModel(390, null, null, 1));

        jLabel3.setText("Sampai");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(awal_du)
                    .addComponent(akhir_du)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(awal_du, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akhir_du, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel14.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 0, 204));
        jPanel15.setMinimumSize(new java.awt.Dimension(50, 100));
        jPanel15.setPreferredSize(new java.awt.Dimension(50, 113));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Data Latih");

        awal_dl.setModel(new javax.swing.SpinnerNumberModel(391, null, null, 1));

        akhir_dl.setModel(new javax.swing.SpinnerNumberModel(781, null, null, 1));

        jLabel5.setText("Sampai");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(awal_dl)
                    .addComponent(akhir_dl)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(awal_dl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(akhir_dl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jPanel15.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel15);

        create_scnearion.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(295, 30));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jPanel8.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        buatSkenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        buatSkenario.setToolTipText("tambah skenario");
        buatSkenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buatSkenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatSkenarioActionPerformed(evt);
            }
        });
        jPanel8.add(buatSkenario, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(50, 29));
        jPanel9.setLayout(new java.awt.BorderLayout());

        lihatPartisiData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/look.png"))); // NOI18N
        lihatPartisiData.setToolTipText("Lihat Partisi Data");
        lihatPartisiData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatPartisiData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatPartisiDataActionPerformed(evt);
            }
        });
        jPanel9.add(lihatPartisiData, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel9);

        create_scnearion.add(jPanel7);

        custome_skenario_pengujian.add(create_scnearion);

        list_scenario.setBackground(new java.awt.Color(102, 204, 0));
        list_scenario.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel19.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Daftar Skenario");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel7)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel19);

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        list_skenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        list_skenario.setFocusCycleRoot(true);
        list_skenario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_skenarioValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(list_skenario);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel2);

        jPanel18.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel18.setLayout(new java.awt.BorderLayout());

        hapusSkenario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        hapusSkenario.setText("Skenario");
        hapusSkenario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusSkenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusSkenarioActionPerformed(evt);
            }
        });
        jPanel18.add(hapusSkenario, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel18);

        list_scenario.add(jPanel3, java.awt.BorderLayout.CENTER);

        custome_skenario_pengujian.add(list_scenario);

        jPanel1.add(custome_skenario_pengujian);

        custome_pengujian.setBackground(new java.awt.Color(51, 51, 255));
        custome_pengujian.setPreferredSize(new java.awt.Dimension(750, 559));
        custome_pengujian.setLayout(new javax.swing.BoxLayout(custome_pengujian, javax.swing.BoxLayout.PAGE_AXIS));

        Daftar_percobaan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Daftar_percobaan.setMaximumSize(new java.awt.Dimension(2147483647, 150));
        Daftar_percobaan.setPreferredSize(new java.awt.Dimension(750, 130));
        Daftar_percobaan.setLayout(new javax.swing.BoxLayout(Daftar_percobaan, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("    Daftar Percobaan");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setPreferredSize(new java.awt.Dimension(141, 30));
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jPanel22.add(jLabel8, java.awt.BorderLayout.CENTER);

        Daftar_percobaan.add(jPanel22);

        jPanel21.setPreferredSize(new java.awt.Dimension(750, 130));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabel_percobaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_percobaan", "Tipe Algoritma", "Akurasi(%)", "Waktu eksekusi(detik)"
            }
        ));
        tabel_percobaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabel_percobaan.setPreferredSize(new java.awt.Dimension(300, 80));
        tabel_percobaan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabel_percobaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_percobaanMouseClicked(evt);
            }
        });
        tabel_percobaan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabel_percobaanPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_percobaan);
        if (tabel_percobaan.getColumnModel().getColumnCount() > 0) {
            tabel_percobaan.getColumnModel().getColumn(0).setResizable(false);
            tabel_percobaan.getColumnModel().getColumn(1).setResizable(false);
            tabel_percobaan.getColumnModel().getColumn(2).setResizable(false);
            tabel_percobaan.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel21.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        hapusPercobaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bin.png"))); // NOI18N
        hapusPercobaan.setText("Percobaan");
        hapusPercobaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusPercobaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPercobaanActionPerformed(evt);
            }
        });
        jPanel21.add(hapusPercobaan, java.awt.BorderLayout.PAGE_END);

        Daftar_percobaan.add(jPanel21);

        custome_pengujian.add(Daftar_percobaan);

        custome_algorithm.setLayout(new javax.swing.BoxLayout(custome_algorithm, javax.swing.BoxLayout.LINE_AXIS));

        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel23.setMinimumSize(new java.awt.Dimension(300, 194));
        jPanel23.setPreferredSize(new java.awt.Dimension(300, 429));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setPreferredSize(new java.awt.Dimension(304, 20));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/setting.png"))); // NOI18N
        jLabel9.setText("Algoritma Klasifikasi");
        jPanel26.add(jLabel9, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel26);

        jPanel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel27.setPreferredSize(new java.awt.Dimension(304, 50));

        opsi_pso.setText(" Gunakan Pembobotan Fitur PSO");
        opsi_pso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsi_psoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsi_pso)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opsi_pso, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel23.add(jPanel27);

        jPanel25.setPreferredSize(new java.awt.Dimension(310, 337));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jPanel28.setLayout(new java.awt.BorderLayout());
        jScrollPane2.setViewportView(jPanel28);

        jPanel25.add(jScrollPane2, java.awt.BorderLayout.LINE_END);

        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.PAGE_AXIS));

        Generasi_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Generasi_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        Generasi_panel.setLayout(new javax.swing.BoxLayout(Generasi_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel31.setPreferredSize(new java.awt.Dimension(10, 69));
        jPanel31.setLayout(new java.awt.BorderLayout());

        label_stoping_criteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Generasi", "  Akurasi" }));
        label_stoping_criteria.setMaximumSize(new java.awt.Dimension(15, 32767));
        label_stoping_criteria.setMinimumSize(new java.awt.Dimension(15, 20));
        label_stoping_criteria.setPreferredSize(new java.awt.Dimension(15, 20));
        jPanel31.add(label_stoping_criteria, java.awt.BorderLayout.CENTER);

        Generasi_panel.add(jPanel31);

        jPanel34.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel34.setLayout(new java.awt.BorderLayout());

        label_input_stoping_point.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_stoping_point.setText("1000");
        label_input_stoping_point.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel34.add(label_input_stoping_point, java.awt.BorderLayout.CENTER);

        Generasi_panel.add(jPanel34);

        jPanel29.add(Generasi_panel);

        populasi_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        populasi_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        populasi_panel.setLayout(new javax.swing.BoxLayout(populasi_panel, javax.swing.BoxLayout.LINE_AXIS));

        populasi_.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel11.setText("Populasi");

        javax.swing.GroupLayout populasi_Layout = new javax.swing.GroupLayout(populasi_);
        populasi_.setLayout(populasi_Layout);
        populasi_Layout.setHorizontalGroup(
            populasi_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(populasi_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        populasi_Layout.setVerticalGroup(
            populasi_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        populasi_panel.add(populasi_);

        jPanel35.setLayout(new java.awt.BorderLayout());

        label_input_populasi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_populasi.setText("5");
        jPanel35.add(label_input_populasi, java.awt.BorderLayout.CENTER);

        populasi_panel.add(jPanel35);

        jPanel29.add(populasi_panel);

        c1_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c1_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        c1_panel.setLayout(new javax.swing.BoxLayout(c1_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel36.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel12.setText("c1");

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        c1_panel.add(jPanel36);

        jPanel37.setLayout(new java.awt.BorderLayout());

        label_input_c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_c1.setText("0.2");
        jPanel37.add(label_input_c1, java.awt.BorderLayout.CENTER);

        c1_panel.add(jPanel37);

        jPanel29.add(c1_panel);

        c2_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        c2_panel.setPreferredSize(new java.awt.Dimension(294, 30));
        c2_panel.setLayout(new javax.swing.BoxLayout(c2_panel, javax.swing.BoxLayout.LINE_AXIS));

        jPanel40.setPreferredSize(new java.awt.Dimension(100, 69));

        jLabel14.setText("c2");

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        c2_panel.add(jPanel40);

        jPanel41.setLayout(new java.awt.BorderLayout());

        label_input_c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        label_input_c2.setText("0.3");
        jPanel41.add(label_input_c2, java.awt.BorderLayout.CENTER);

        c2_panel.add(jPanel41);

        jPanel29.add(c2_panel);

        jPanel25.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel25);

        jPanel24.setPreferredSize(new java.awt.Dimension(304, 20));
        jPanel24.setLayout(new java.awt.BorderLayout());

        mulaiKlasifikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/start.png"))); // NOI18N
        mulaiKlasifikasi.setText("Naive Bayes Classification");
        mulaiKlasifikasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mulaiKlasifikasi.setPreferredSize(new java.awt.Dimension(105, 20));
        mulaiKlasifikasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiKlasifikasiActionPerformed(evt);
            }
        });
        jPanel24.add(mulaiKlasifikasi, java.awt.BorderLayout.CENTER);

        jPanel23.add(jPanel24);

        custome_algorithm.add(jPanel23);

        jPanel20.setMaximumSize(new java.awt.Dimension(449, 2147483647));
        jPanel20.setLayout(new javax.swing.BoxLayout(jPanel20, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel30.setPreferredSize(new java.awt.Dimension(442, 445));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jPanel44.setBackground(new java.awt.Color(255, 255, 255));
        jPanel44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel44.setLayout(new java.awt.BorderLayout());

        jPanel45.setBackground(new java.awt.Color(255, 255, 255));
        jPanel45.setAutoscrolls(true);
        jPanel45.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPanel45.setPreferredSize(new java.awt.Dimension(420, 450));
        jPanel45.setVerifyInputWhenFocusTarget(false);
        jPanel45.setLayout(new java.awt.BorderLayout());

        log_panel.setBackground(new java.awt.Color(255, 255, 255));
        log_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log Percobaan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        log_panel.setAutoscrolls(true);
        log_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        label_tipe.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        label_tipe.setText("Tipe");

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel32.setText("Data Latih ");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Akurasi");

        label_akurasi.setText("90%");

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel34.setText("Data Uji");

        label_porsi_dl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_porsi_dl.setText("0");

        label_porsi_du.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_porsi_du.setText("0");

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel38.setText("Jumlah");

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel39.setText("Jumlah");

        label_jumlah_dl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_jumlah_dl.setText("0");

        label_jumlah_du.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_jumlah_du.setText("0");

        panel_PSO_konf.setBackground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel20.setText("Generasi :");

        label_generasi.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_generasi.setText("0");

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel22.setText("Populasi :");

        label_populasi.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_populasi.setText("0");

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel21.setText("c1 :");

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel24.setText("c2 :");

        label_c1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_c1.setText("0");

        label_c2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_c2.setText("0");

        label_bobot_fitur.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        label_bobot_fitur.setText("0");

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel27.setText("Tertinggi :");

        javax.swing.GroupLayout panel_PSO_konfLayout = new javax.swing.GroupLayout(panel_PSO_konf);
        panel_PSO_konf.setLayout(panel_PSO_konfLayout);
        panel_PSO_konfLayout.setHorizontalGroup(
            panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                        .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(label_generasi))
                            .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(label_populasi)))
                        .addGap(123, 123, 123)
                        .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_c1)
                            .addComponent(label_c2)))
                    .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(label_bobot_fitur)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panel_PSO_konfLayout.setVerticalGroup(
            panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PSO_konfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(label_generasi)
                    .addComponent(jLabel21)
                    .addComponent(label_c1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(label_populasi)
                    .addComponent(jLabel24)
                    .addComponent(label_c2))
                .addGap(27, 27, 27)
                .addGroup(panel_PSO_konfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(label_bobot_fitur))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout log_panelLayout = new javax.swing.GroupLayout(log_panel);
        log_panel.setLayout(log_panelLayout);
        log_panelLayout.setHorizontalGroup(
            log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_panelLayout.createSequentialGroup()
                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(log_panelLayout.createSequentialGroup()
                        .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(log_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33))
                            .addGroup(log_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_tipe)
                                    .addGroup(log_panelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel32))))))
                        .addGap(34, 34, 34)
                        .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_akurasi)
                            .addGroup(log_panelLayout.createSequentialGroup()
                                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_porsi_dl)
                                    .addComponent(label_porsi_du))
                                .addGap(65, 65, 65)
                                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39))
                                .addGap(61, 61, 61)
                                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_jumlah_du)
                                    .addComponent(label_jumlah_dl)))))
                    .addGroup(log_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_PSO_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        log_panelLayout.setVerticalGroup(
            log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(log_panelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(label_tipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(label_porsi_dl)
                    .addComponent(jLabel38)
                    .addComponent(label_jumlah_dl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(label_porsi_du)
                    .addComponent(jLabel39)
                    .addComponent(label_jumlah_du))
                .addGap(27, 27, 27)
                .addComponent(panel_PSO_konf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(log_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(label_akurasi))
                .addGap(28, 28, 28))
        );

        jPanel45.add(log_panel, java.awt.BorderLayout.CENTER);

        jScrollPane4.setViewportView(jPanel45);

        jPanel44.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel20.add(jPanel30);

        jPanel32.setBackground(new java.awt.Color(204, 204, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label_rerata_akurasi_skenario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label_rerata_akurasi_skenario.setText("0%");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setText("Rata-rata Akurasi");

        label_log_skenario.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label_log_skenario.setText("Skenario");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_log_skenario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(label_rerata_akurasi_skenario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(label_log_skenario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_rerata_akurasi_skenario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(jPanel32);

        custome_algorithm.add(jPanel20);

        custome_pengujian.add(custome_algorithm);

        jPanel1.add(custome_pengujian);

        Main_panel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Dashboard", Main_panel);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lihatPartisiDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatPartisiDataActionPerformed
        int posisi_awal_du = Integer.parseInt(this.awal_du.getModel().getValue().toString());
        int posisi_akhir_du = Integer.parseInt(this.akhir_du.getModel().getValue().toString());
        int posisi_awal_dl = Integer.parseInt(this.awal_dl.getModel().getValue().toString());
        int posisi_akhir_dl = Integer.parseInt(this.akhir_dl.getModel().getValue().toString());
        this.main_controller.tampilkanFramePartisiData(posisi_awal_dl,posisi_akhir_dl, posisi_awal_du,posisi_akhir_du);
    }//GEN-LAST:event_lihatPartisiDataActionPerformed

    private void buatSkenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatSkenarioActionPerformed
        String nama = this.nama_skenario.getText();
        int posisi_awal_du = Integer.parseInt(this.awal_du.getModel().getValue().toString());
        int posisi_akhir_du = Integer.parseInt(this.akhir_du.getModel().getValue().toString());
        int posisi_awal_dl = Integer.parseInt(this.awal_dl.getModel().getValue().toString());
        int posisi_akhir_dl = Integer.parseInt(this.akhir_dl.getModel().getValue().toString());
        this.daftar_skenario = this.main_controller.buatSkenario(nama, posisi_awal_dl,posisi_akhir_dl, posisi_awal_du,posisi_akhir_du);
        this.drawListSkenario();
    }//GEN-LAST:event_buatSkenarioActionPerformed

    private void hapusSkenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusSkenarioActionPerformed
       int index_hapus = 0;
       int id_skenario = 0;
        for(int i=0;i<this.daftar_skenario.size();i++){
           if(this.daftar_skenario.get(i).getNama().equalsIgnoreCase(this.list_skenario.getSelectedValue())){
               index_hapus = i;
               id_skenario = this.daftar_skenario.get(i).getId_skenario();
               break;
           }
        }
        this.main_controller.hapusSkenario(id_skenario);
        this.daftar_skenario.remove(index_hapus);
        this.drawListSkenario();       
    }//GEN-LAST:event_hapusSkenarioActionPerformed

    private void hapusPercobaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPercobaanActionPerformed
        int id_percobaan = Integer.parseInt(this.tabel_percobaan.getValueAt(this.tabel_percobaan.getSelectedRow(), 0).toString());      
        for(Skenario skenario : this.daftar_skenario){
            if(skenario.getNama().equalsIgnoreCase(this.list_skenario.getSelectedValue())){
                skenario.hapusPercobaan(id_percobaan);
                break;
            }
        }
        this.main_controller.hapusPercobaan(id_percobaan);
        this.aktifkanSkenario(this.list_skenario.getSelectedValue());
    }//GEN-LAST:event_hapusPercobaanActionPerformed

    private void list_skenarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_skenarioValueChanged
        this.aktifkanSkenario(this.list_skenario.getSelectedValue());
    }//GEN-LAST:event_list_skenarioValueChanged

    private void tabel_percobaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_percobaanMouseClicked
        try{
            int id = Integer.parseInt(this.tabel_percobaan.getValueAt(this.tabel_percobaan.getSelectedRow(), 0).toString());
            Percobaan percobaan_terpilih = null;
            for(Skenario skenario : this.daftar_skenario){
                for(Percobaan percobaan : skenario.getDaftar_percobaan()){
                    if(id == percobaan.getId_percobaan()){
                        percobaan_terpilih = percobaan;
                        this.drawLogPercobaan(skenario, percobaan_terpilih);
                        break;
                    }
                }
            }
        }
        catch(Exception io){
            // di luar tabel
        }
    }//GEN-LAST:event_tabel_percobaanMouseClicked

    private void mulaiKlasifikasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiKlasifikasiActionPerformed
        Skenario skenario = this.getSkenarioBasedOnName(this.list_skenario.getSelectedValue());
        Percobaan percobaan_baru = null;
        if(!this.opsi_pso.isSelected()){
          percobaan_baru = this.main_controller.doNaiveBayesClassifier(skenario);
        }else{
           HashMap<String, String> konfigurasi = new HashMap<String, String>();
           konfigurasi.put("Stoping_criteria", this.label_stoping_criteria.getSelectedItem().toString());
           konfigurasi.put("Stoping_point",this.label_input_stoping_point.getText());
           konfigurasi.put("Populasi", this.label_input_populasi.getText());
           konfigurasi.put("c1", this.label_input_c1.getText());
           konfigurasi.put("c2", this.label_input_c2.getText());      
           percobaan_baru = this.main_controller.doPSONaiveBayesClassifier(skenario, konfigurasi);
        }
        skenario.tambahPercobaan(percobaan_baru);
        this.aktifkanSkenario(skenario.getNama());
    }//GEN-LAST:event_mulaiKlasifikasiActionPerformed

    private void opsi_psoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsi_psoActionPerformed
       if(this.opsi_pso.isSelected()){
           this.enableKonfigurasiPSO(true);
       }
       else{
           this.enableKonfigurasiPSO(false);
       }
    }//GEN-LAST:event_opsi_psoActionPerformed

    private void tabel_percobaanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabel_percobaanPropertyChange
         DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int i=0;i<this.tabel_percobaan.getColumnCount();i++){
           this.tabel_percobaan.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }    
    }//GEN-LAST:event_tabel_percobaanPropertyChange
    
    private void enableKonfigurasiPSO(boolean cond){
        
        this.label_input_stoping_point.setEnabled(cond);
        this.Generasi_panel.setEnabled(cond);
        this.label_input_populasi.setEnabled(cond);
        this.label_input_c1.setEnabled(cond);
        this.label_input_c2.setEnabled(cond);
        this.label_stoping_criteria.setEnabled(cond);
    
    }
    
    private void aktifkanSkenario(String nama_skenario){
       Skenario skenario_terpilih;
        DefaultTableModel model_tabel = (DefaultTableModel) this.tabel_percobaan.getModel();  
       if(this.daftar_skenario.size()!=0){
          if(nama_skenario == null){
              skenario_terpilih = this.daftar_skenario.get(0);
          }else {
              skenario_terpilih = this.getSkenarioBasedOnName(nama_skenario);
          }
          DecimalFormat df = new DecimalFormat("#.##");
          
          if(skenario_terpilih.getDaftar_percobaan().size() != 0){
                 model_tabel.setRowCount(0);
                this.label_log_skenario.setText(skenario_terpilih.getNama());
                this.label_rerata_akurasi_skenario.setText(Double.parseDouble(df.format(skenario_terpilih.getRerataAkurasiSkenario()).replaceAll(",","."))+" %");
                Object object[] = new Object[4];
                for(Percobaan percobaan : skenario_terpilih.getDaftar_percobaan()){
                    object[0] =  percobaan.getId_percobaan();
                    object[1] =  percobaan.getTipe();
                    object[2] =  percobaan.getAkurasi();
                    object[3] =  percobaan.getWaktu();
                    model_tabel.addRow(object);
                    this.aktifkanDaftarPercobaan(0);
                }    
          }else{
              model_tabel.setRowCount(0);
              this.aktifkanDaftarPercobaan(-1);
          }
          
       }else{
           model_tabel.setRowCount(0);
           this.aktifkanDaftarPercobaan(-1);
       }
       
    }
    
    private void aktifkanDaftarPercobaan(int index){
        if(index != -1){
            Skenario skenario_terpilih = this.getSkenarioBasedOnName(this.list_skenario.getSelectedValue());
            if(skenario_terpilih == null){
                skenario_terpilih = this.daftar_skenario.get(0);
            }
            this.tabel_percobaan.setRowSelectionInterval(index, index);
            Percobaan percobaan = skenario_terpilih.getPercobaan(Integer.parseInt(this.tabel_percobaan.getValueAt(index,0).toString()));
            this.drawLogPercobaan(skenario_terpilih, percobaan);     
        }
        else{
            this.clearSkenario();
        }          
    }
    
    private void drawLogPercobaan(Skenario skenario, Percobaan percobaan_terpilih){
       
        this.label_tipe.setText(percobaan_terpilih.getTipe());
        if(percobaan_terpilih.getTipe().equalsIgnoreCase("NB")){
            this.panel_PSO_konf.hide();
        }
        else{
            this.panel_PSO_konf.show();
            this.label_generasi.setText(percobaan_terpilih.getGenerasi()+"");
            this.label_populasi.setText(percobaan_terpilih.getPopulasi()+"");
            this.label_c1.setText(percobaan_terpilih.getC1()+"");
            this.label_c2.setText(percobaan_terpilih.getC2()+"");
            this.label_bobot_fitur.setText(percobaan_terpilih.getBobot());
        }
      
        this.label_porsi_dl.setText(skenario.getAwal_dl()+" - "+skenario.getAkhir_dl());
        this.label_porsi_du.setText(skenario.getAwal_du()+" - "+skenario.getAkhir_du());
        this.label_jumlah_dl.setText((skenario.getAkhir_dl()-(skenario.getAwal_dl()-1))+"");
        this.label_jumlah_du.setText((skenario.getAkhir_du()-(skenario.getAwal_du()-1))+"");
        this.label_akurasi.setText(percobaan_terpilih.getAkurasi()+" %");
    }
    
    
    private void clearSkenario(){
        this.label_tipe.setText("-");
        this.label_generasi.setText("-");
        this.label_populasi.setText("-");
        this.label_c1.setText("-");
        this.label_c2.setText("-");
        this.label_porsi_dl.setText("-");
        this.label_porsi_du.setText("-");
        this.label_jumlah_dl.setText("-");
        this.label_jumlah_du.setText("-");
        this.label_akurasi.setText("-");
        this.label_rerata_akurasi_skenario.setText("0 %");
        this.label_bobot_fitur.setText("-");
    }
    
    private Skenario getSkenarioBasedOnName(String nama_skenario){
        Skenario skenario_terpilih = null;
         for(Skenario skenario : this.daftar_skenario){
           if(skenario.getNama().equalsIgnoreCase(nama_skenario)){
               skenario_terpilih = skenario;
               break;
           }
       }
        return skenario_terpilih;
    }
    
    private void drawListSkenario(){
        DefaultListModel list = new DefaultListModel();
        for(Skenario skenario : this.daftar_skenario){
            list.addElement(skenario.getNama());
        }
        this.list_skenario.setModel(list);
        this.list_skenario.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Daftar_percobaan;
    private javax.swing.JPanel Generasi_panel;
    private javax.swing.JPanel Home_Panel;
    private javax.swing.JPanel Main_panel;
    private javax.swing.JSpinner akhir_dl;
    private javax.swing.JSpinner akhir_du;
    private javax.swing.JSpinner awal_dl;
    private javax.swing.JSpinner awal_du;
    private javax.swing.JButton buatSkenario;
    private javax.swing.JPanel c1_panel;
    private javax.swing.JPanel c2_panel;
    private javax.swing.JPanel create_scnearion;
    private javax.swing.JPanel custome_algorithm;
    private javax.swing.JPanel custome_pengujian;
    private javax.swing.JPanel custome_skenario_pengujian;
    private javax.swing.JButton hapusPercobaan;
    private javax.swing.JButton hapusSkenario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label_akurasi;
    private javax.swing.JLabel label_bobot_fitur;
    private javax.swing.JLabel label_c1;
    private javax.swing.JLabel label_c2;
    private javax.swing.JLabel label_generasi;
    private javax.swing.JTextField label_input_c1;
    private javax.swing.JTextField label_input_c2;
    private javax.swing.JTextField label_input_populasi;
    private javax.swing.JTextField label_input_stoping_point;
    private javax.swing.JLabel label_jumlah_dl;
    private javax.swing.JLabel label_jumlah_du;
    private javax.swing.JLabel label_log_skenario;
    private javax.swing.JLabel label_populasi;
    private javax.swing.JLabel label_porsi_dl;
    private javax.swing.JLabel label_porsi_du;
    private javax.swing.JLabel label_rerata_akurasi_skenario;
    private javax.swing.JComboBox<String> label_stoping_criteria;
    private javax.swing.JLabel label_tipe;
    private javax.swing.JButton lihatPartisiData;
    private javax.swing.JPanel list_scenario;
    private javax.swing.JList<String> list_skenario;
    private javax.swing.JPanel log_panel;
    private javax.swing.JButton mulaiKlasifikasi;
    private javax.swing.JTextField nama_skenario;
    private javax.swing.JRadioButton opsi_pso;
    private javax.swing.JPanel panel_PSO_konf;
    private javax.swing.JPanel populasi_;
    private javax.swing.JPanel populasi_panel;
    private javax.swing.JTable tabel_percobaan;
    // End of variables declaration//GEN-END:variables
}
