/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Data;
import Model.Fitur;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author M.Hakim Amransyah
 */
public class PartisiData extends javax.swing.JFrame {

   private Data latih;
   private Data uji;
   
    public PartisiData(Data latih, Data uji) {
        initComponents();
        this.latih = latih;
        this.uji = uji;
        this.setTabel(this.latih,"Data Latih");
    }
    
    private void setTabel(Data data, String jenis_data){
        DefaultTableModel model_tabel = null;
        switch(jenis_data){
          case "Data Latih" : 
              model_tabel = (DefaultTableModel) this.tabel_data_latih.getModel();
              break;
          case "Data Uji": 
              model_tabel = (DefaultTableModel) this.tabel_data_uji.getModel();
              break;
        }
        model_tabel.setRowCount(0);
//        model_tabel.setColumnCount(data.getJumlahAtributData());
        for(Fitur fitur : data.getFitur()){
             Object object[] = new Object[data.getJumlahAtributData()];
             object[0] = fitur.getNomor();
             object[1] = fitur.getSubjek_id();
             
             int i=2;
             for(Double nilai_fitur : fitur.getNilaiFitur()){
                object[i] = nilai_fitur;
                i++;
             }
             
             object[object.length-1] = fitur.getLabel();
             model_tabel.addRow(object);
        }
        this.jenis_data.setText(data.getJenis_data());
        this.jumlah_parkinson.setText(data.getJumlahSebaranData("Parkinson")+"");
        this.jumlah_tidak_parkinson.setText(data.getJumlahSebaranData("Tidak")+"");
        this.jumlah_Seluruh.setText(data.getJumlahSeluruhData()+"");
    }

    private PartisiData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lihatDataLatih = new javax.swing.JButton();
        lihatDataUji = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jumlah_parkinson = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jumlah_tidak_parkinson = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jumlah_Seluruh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_data = new javax.swing.JPanel();
        view_data_latih = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_latih = new javax.swing.JTable();
        view_data_uji = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_data_uji = new javax.swing.JTable();
        jenis_data = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Data");

        lihatDataLatih.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lihatDataLatih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/look.png"))); // NOI18N
        lihatDataLatih.setText("Data Latih");
        lihatDataLatih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatDataLatih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataLatihActionPerformed(evt);
            }
        });

        lihatDataUji.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lihatDataUji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/look.png"))); // NOI18N
        lihatDataUji.setText("Data Uji");
        lihatDataUji.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lihatDataUji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataUjiActionPerformed(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 44));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jumlah_parkinson.setBackground(new java.awt.Color(255, 255, 255));
        jumlah_parkinson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlah_parkinson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sick.png"))); // NOI18N
        jumlah_parkinson.setText("130");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jumlah_parkinson)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlah_parkinson, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);

        jumlah_tidak_parkinson.setBackground(new java.awt.Color(255, 255, 255));
        jumlah_tidak_parkinson.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlah_tidak_parkinson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/smile.png"))); // NOI18N
        jumlah_tidak_parkinson.setText("130");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jumlah_tidak_parkinson)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlah_tidak_parkinson, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel5);

        jumlah_Seluruh.setBackground(new java.awt.Color(255, 255, 255));
        jumlah_Seluruh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlah_Seluruh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/data.png"))); // NOI18N
        jumlah_Seluruh.setText("130");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jumlah_Seluruh)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlah_Seluruh, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setText("Data");

        panel_data.setLayout(new java.awt.CardLayout());

        view_data_latih.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabel_data_latih.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Id Subjek", "fitur 1", "fitur 2", "fitur 3", "fitur 4", "fitur 5", "fitur 6", "fitur 7", "fitur 8", "fitur 9", "fitur 10", "fitur 11", "fitur 12", "fitur 13", "fitur 14", "fitur 15", "fitur 16", "fitur 17", "fitur 18", "fitur 19", "fitur 20", "fitur 21", "fitur 22", "fitur 23", "fitur 24", "fitur 25", "fitur 26", "label"
            }
        ));
        tabel_data_latih.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_data_latih.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabel_data_latihPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data_latih);

        view_data_latih.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panel_data.add(view_data_latih, "card2");

        view_data_uji.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabel_data_uji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Id Subjek", "fitur 1", "fitur 2", "fitur 3", "fitur 4", "fitur 5", "fitur 6", "fitur 7", "fitur 8", "fitur 9", "fitur 10", "fitur 11", "fitur 12", "fitur 13", "fitur 14", "fitur 15", "fitur 16", "fitur 17", "fitur 18", "fitur 19", "fitur 20", "fitur 21", "fitur 22", "fitur 23", "fitur 24", "fitur 25", "fitur 26", "label"
            }
        ));
        tabel_data_uji.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabel_data_uji.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabel_data_ujiPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_data_uji);

        view_data_uji.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        panel_data.add(view_data_uji, "card2");

        jenis_data.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jenis_data.setText("jenis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_data, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lihatDataLatih, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lihatDataUji, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jenis_data)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis_data)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_data, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lihatDataLatih, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lihatDataUji, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lihatDataLatihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataLatihActionPerformed
        this.panel_data.removeAll();
        this.panel_data.add(this.view_data_latih);
        this.panel_data.repaint();
        this.panel_data.revalidate();
        this.setTabel(this.latih,"Data Latih");
    }//GEN-LAST:event_lihatDataLatihActionPerformed

    private void lihatDataUjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataUjiActionPerformed
        this.panel_data.removeAll();
        this.panel_data.add(this.view_data_uji);
        this.panel_data.repaint();
        this.panel_data.revalidate();
        this.setTabel(this.uji,"Data Uji");
    }//GEN-LAST:event_lihatDataUjiActionPerformed

    private void tabel_data_latihPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabel_data_latihPropertyChange
         DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int i=0;i<this.tabel_data_latih.getColumnCount();i++){
           this.tabel_data_latih.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }    
    }//GEN-LAST:event_tabel_data_latihPropertyChange

    private void tabel_data_ujiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabel_data_ujiPropertyChange
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        for(int i=0;i<this.tabel_data_uji.getColumnCount();i++){
           this.tabel_data_uji.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }    
    }//GEN-LAST:event_tabel_data_ujiPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartisiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartisiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartisiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartisiData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartisiData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jenis_data;
    private javax.swing.JLabel jumlah_Seluruh;
    private javax.swing.JLabel jumlah_parkinson;
    private javax.swing.JLabel jumlah_tidak_parkinson;
    private javax.swing.JButton lihatDataLatih;
    private javax.swing.JButton lihatDataUji;
    private javax.swing.JPanel panel_data;
    private javax.swing.JTable tabel_data_latih;
    private javax.swing.JTable tabel_data_uji;
    private javax.swing.JPanel view_data_latih;
    private javax.swing.JPanel view_data_uji;
    // End of variables declaration//GEN-END:variables
}
